import fs from 'fs';
import path from 'path';
import { Router } from 'express';
import swaggerUi from 'swagger-ui-express';

const router = Router();

// Path to swagger file
const swaggerFilePath = path.resolve(process.cwd(), 'server/swagger.json');

let swaggerDocument = {
	openapi: '3.0.0',
	info: {
		title: 'SDK Test Server',
		version: '1.0.0',
		description: 'This is an autogenerated Swagger file.'
	},
	paths: {}
};

// Load swagger file if present
if (fs.existsSync(swaggerFilePath)) {
	try {
		const data = fs.readFileSync(swaggerFilePath, 'utf8');
		swaggerDocument = JSON.parse(data);
	} catch (err) {
		console.error('⚠️ Failed to read swagger.json:', err);
	}
} else {
	console.warn('⚠️ No swagger.json file found. Serving default template.');
}

router.use('/', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

export default router;
